version: "3.8"

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: livro
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped

volumes:
    postgres-data: