spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: true

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/livro
    username: postgres
    password: postgres
